const res = [
    {
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "16:20",
    "arrival_date": "12.05.18",
    "arrival_time": "22:10",
    "carrier": "TK",
    "stops": 3,
    "price": 1240
},
{
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "17:20",
    "arrival_date": "12.05.18",
    "arrival_time": "23:50",
    "carrier": "S7",
    "stops": 1,
    "price": 1310
},
{
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "12:10",
    "arrival_date": "12.05.18",
    "arrival_time": "18:10",
    "carrier": "SU",
    "stops": 0,
    "price": 1530
},
{
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "17:00",
    "arrival_date": "12.05.18",
    "arrival_time": "23:30",
    "carrier": "TK",
    "stops": 2,
    "price": 1100
},
{
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "12:10",
    "arrival_date": "12.05.18",
    "arrival_time": "20:15",
    "carrier": "BA",
    "stops": 3,
    "price": 1340
},
{
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "9:40",
    "arrival_date": "12.05.18",
    "arrival_time": "19:25",
    "carrier": "SU",
    "stops": 3,
    "price": 1240
},
{
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "17:10",
    "arrival_date": "12.05.18",
    "arrival_time": "23:45",
    "carrier": "TK",
    "stops": 1,
    "price": 1360
},
{
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "6:10",
    "arrival_date": "12.05.18",
    "arrival_time": "15:25",
    "carrier": "TK",
    "stops": 0,
    "price": 1420
},
{
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "16:50",
    "arrival_date": "12.05.18",
    "arrival_time": "23:35",
    "carrier": "SU",
    "stops": 1,
    "price": 1670
},
{
    "origin": "VVO",
    "origin_name": "Kyiv",
    "destination": "TLV",
    "destination_name": "Tel Aviv",
    "departure_date": "12.05.18",
    "departure_time": "6:10",
    "arrival_date": "12.05.18",
    "arrival_time": "16:15",
    "carrier": "S7",
    "stops": 0,
    "price": 1740
}
]
export default res

